### ISSUE TITLE
Проблема с запуском сервера Django PyCharm

### ISSUE THREAD

**Issue by dasuaser** [ruRust/rustycrate.ru#239]
```
M:\untitled>python manage.py runserver
Performing system checks...

System check identified some issues:

WARNINGS:
?: (1_8.W001) The standalone TEMPLATE_* settings were deprecated in Django 1.8 and the TEMPLATES dictionary takes precedence. You must put the values of the following settings
into your default TEMPLATES dict: TEMPLATE_DIRS.

System check identified 1 issue (0 silenced).
September 11, 2017 - 00:42:17
Django version 1.11.5, using settings 'untitled.settings'
Starting development server at http://127.0.0.1:8000/
Quit the server with CTRL-BREAK.
Unhandled exception in thread started by <function check_errors.<locals>.wrapper at 0x031D9420>
Traceback (most recent call last):
  File "C:\Program Files (x86)\Python36-32\lib\site-packages\django\utils\autoreload.py", line 228, in wrapper
    fn(*args, **kwargs)
  File "C:\Program Files (x86)\Python36-32\lib\site-packages\django\core\management\commands\runserver.py", line 149, in inner_run
    ipv6=self.use_ipv6, threading=threading, server_cls=self.server_cls)
  File "C:\Program Files (x86)\Python36-32\lib\site-packages\django\core\servers\basehttp.py", line 164, in run
    httpd = httpd_cls(server_address, WSGIRequestHandler, ipv6=ipv6)
  File "C:\Program Files (x86)\Python36-32\lib\site-packages\django\core\servers\basehttp.py", line 74, in __init__
    super(WSGIServer, self).__init__(*args, **kwargs)
  File "C:\Program Files (x86)\Python36-32\lib\socketserver.py", line 453, in __init__
    self.server_bind()
  File "C:\Program Files (x86)\Python36-32\lib\wsgiref\simple_server.py", line 50, in server_bind
    HTTPServer.server_bind(self)
  File "C:\Program Files (x86)\Python36-32\lib\http\server.py", line 138, in server_bind
    self.server_name = socket.getfqdn(host)
  File "C:\Program Files (x86)\Python36-32\lib\socket.py", line 673, in getfqdn
    hostname, aliases, ipaddrs = gethostbyaddr(name)
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xcf in position 7: invalid continuation byte

```
В пути нету кирилицы, в имени пользователя тоже.

**Comment by mkpankov** [comment]
Не имеет отношения к языку Rust или сайту rustycrate.ru, закрываю.
